### PR TITLE
Update screenshot_darwin.go

### PR DESCRIPTION
**Pull request by k4sud0n**
'CGDisplayCreateImageForRect' is unavailable: obsoleted in macOS 15.0

Using ScreenCaptureKit instead.

### CODE REVIEW

**Comment by ro31337** [comment]
Why it was closed @k4sud0n ? If I can ask

**Comment by ro31337** [comment]
@k4sud0n I tried to reproduce it here, but can't capture the actual screenshot (see screencapturekit example): https://github.com/ro31337/screenshot_macos

**Comment by ro31337** [comment]
CC @kbinani ^^^

**Comment by kbinani** [comment]
@ro31337 Thanks for your work. I made a branch called `macos-scikit` yesterday. Could you check if the code in this branch works? https://github.com/kbinani/screenshot/tree/macos-sckit

**Comment by ro31337** [comment]
@kbinani this seems to work fine on my end (tested ScreenCaptureKit specifically)! When the new version is ready, I will test it in the wild, will let you know if I have successful reports from other users.

Also, it would be nice to enable "Issues" section for this repo (if possible). It is in https://github.com/kbinani/screenshot/settings - Scroll down to "Features", there is "Issues" checkbox.

**Comment by kbinani** [comment]
@ro31337 Thank you for trying it out. It really helped 😘

I'm extremely bad at writing things, and I've realized that issues on the GitHub page usually make me stressed.
That's why I disabled the issues page. Sorry about that 😵‍💫

**Comment by ro31337** [comment]
@kbinani no worries, all good! That's what I thought :) Thanks for making the change!

**Pull request closed without merging**
